### ISSUE TITLE
EventHubSpout does not support consumergroups and/or user-properties

### ISSUE THREAD

**Issue by yorgovs** [hdinsight/hdinsight-storm-examples#17]
When using the evenhubspout there is no option to configure a certain consumergroup. However, this option is available in the Java implementation. It is not included in the constructor, but it is available as a property. Can this property be made available through SCP?

On top of that, the eventhubspout only returns the eventdata's message, the user-properties, partitionkey, etc. are not included in the tuple. However these are certainly transmitted. This is probably due to the Java implementation of the spout.

**Comment by rtandonmsft** [comment]
@yorgovs 

The latest update of storm-eventhubs addressed these issues.

- Consumer group usage and fluent api: https://github.com/hdinsight/storm-eventhubs/issues/8
- You can use clojure expression to use an alternative "EventDataScheme" or "BinaryEventDataScheme" to get metadata in a separate field. This may need little more work since we need to create metadata in a compatible C# data type so that the JSON serializer and deserializer can handle that.
