### ISSUE TITLE
Switch-AzureMode CommandNotFound

### ISSUE THREAD

**Issue by ginobili** [hdinsight/hdinsight-storm-examples#20]
I have an issue with running the Kafka Creationscripts. I always get the CommandNotFoundException.
 + CategoryInfo          : ObjectNotFound: (Switch-AzureMode:String) [UploadFileToStorage.ps1], CommandNotFoundException
   + FullyQualifiedErrorId : CommandNotFoundException,UploadFileToStorage.ps1

Any ideas?

**Comment by rtandonmsft** [comment]
@ginobili Kafka comes installed on HDInsight Storm Linux Clusters for developers to try. I would recommend trying that out.

The PowerShell cmdlets have been difficult to keep up to date due to changes. There is a plan to switch to ARM templates that should help alleviate the failures you encounter with those scripts, there is no ETA on that yet.
